### ISSUE TITLE
Team Discussion: General (Day 1)

### ISSUE THREAD

**Issue by tirtha4** [opscaleindia/nerdtalk#1]
Guys let's keep our discussion on this ticket on the project report instead of the other. We don't need to move on to the other one everytime.

Also, for any technical issues, I guess it's best to raise an issue ticket so that whoever is available can help.

Hope that is okay.

**Comment by bhawesh96** [comment]
@tirtha4 
I'll setup the basic client side architecture and push

**Comment by tirtha4** [comment]
@bhawesh96  yeah that will be good.

**Comment by ranjanmishra07** [comment]
@bhawesh96  @tirtha4  should i create npm init on main nerd talk  directory to create package.json and node modules or should i do it in my server directory ?

**Comment by tirtha4** [comment]
I think package.json goes on the main directory. Server specifics can be on the server directory. I think that won't be an issue accessing any component, right?
@bhawesh96 @ranjanmishra07

**Comment by bhawesh96** [comment]
add node_modules in .gitignore
pushing package.json in the server directory should be fine. Even I'll be doing that on client side

**Comment by ranjanmishra07** [comment]
then fine i will start my project under server directory

**Comment by Buffer0x7cd** [comment]
today I will be looking into passport.js for implementing the authentication system.

**Comment by bhawesh96** [comment]
Its okay to not have a responsive UI right?

**Comment by anubsinha** [comment]
@bhawesh96 No. All CSS should be responsive.

**Comment by ranjanmishra07** [comment]
@Manvendra I implementd passport with github right now ...please  look for
how to verify it with mongoose .

**Comment by ranjanmishra07** [comment]
Do we  need to create signin /login form with username , password along
with github and google ?

**Comment by Buffer0x7cd** [comment]
Are you working on the authentication part @ranjanmishra07?

**Comment by ranjanmishra07** [comment]
yes...we will work it together ...please provide links that u find helpful
while searching
..

**Comment by bhawesh96** [comment]
I'm almost done with the UI for login with email and password.
Send me the API urls once you've deployed them

**Comment by Buffer0x7cd** [comment]
okay. I am currently going through mongoose's docs, to get a grasp on it.

**Comment by ranjanmishra07** [comment]
@bhawesh I have not started login with email and password yet . I will send you the api urls as soon as i create them

**Comment by Buffer0x7cd** [comment]
the authentication is based on tokens right? @bhawesh96 @ranjanmishra07

**Comment by tirtha4** [comment]
@ranjanmishra07  @Buffer0x7cd  I guess we don't need the separate logins after all. 

@bhawesh96  if you're done with the basic UI mockup can you push it to the client ? Also the other boilerplate files that react requires. I'll sit with react within an hour. I'll try to figure out the components. I guess it'll be close to Vue components.

**Comment by bhawesh96** [comment]
![screenshot from 2018-01-25 19-12-32](https://user-images.githubusercontent.com/17593065/35391125-bfe94856-0203-11e8-9c9d-da14308192bb.png)
Was offline for a while.
I'm done with UI for login
Signup screen is similar

Suggestions please

**Comment by ranjanmishra07** [comment]
how can we make login page with that contain logging in with email and password (not github and google login) without creating registration page for user to register their credentials (e.g username,name,email,password).? from where will be compare password that we provide with login if it is not already stored in the db while registering the users?
I think we have to make a register route also

**Comment by bhawesh96** [comment]
Oh sorry!
I  just read that we don't need login using email, password

**Comment by bhawesh96** [comment]
@tirtha4 
I'll commit this anyway.
Will clean the registration and custom login and push a fresh one

**Comment by Buffer0x7cd** [comment]
I think it would be good if create a new branch while working and then create PR to merge those changes in @tirtha4  master branch instead of directly pushing into his master branch. this way it will keep any kind of regression out from the master branch.

**Comment by bhawesh96** [comment]
Yep
I pushed to branch `custom-auth` and not to master

**Comment by Buffer0x7cd** [comment]
I have set up a mongo db database on mlab and added configuration files into the project. we can use that DB instead of setting up local branches in everyone system. @tirtha4 @bhawesh96 @ranjanmishra07

**Comment by ranjanmishra07** [comment]
@tirtha4 @bhawesh96  @Buffer0x7cd  i have successfully designed the backend for github login 
but how to connect it with frontend ?

**Comment by ranjanmishra07** [comment]
![screenshot 5](https://user-images.githubusercontent.com/21200740/35392598-7008e5f8-0208-11e8-8617-feebeb96b45d.png)

**Comment by bhawesh96** [comment]
Send me the URL to which I have to send the request for login

**Comment by tirtha4** [comment]
@ranjanmishra07  @bhawesh96  check out this blog

https://medium.com/front-end-hacking/use-github-oauth-as-your-sso-seamlessly-with-react-3e2e3b358fa1

**Comment by bhawesh96** [comment]
Client will make a request to the oAuth url and will get `user` object in return with required attributes and token.
We need that url

**Comment by ranjanmishra07** [comment]
should i commit the changes so that you can deploy and test? @bhawesh96

**Comment by bhawesh96** [comment]
Go ahead.
might need help in setting up the local server

**Comment by tirtha4** [comment]
@ranjanmishra07  can you write in a README.md file within the server folder on how to setup the local server, like the one bhawesh made. All the database and stuff.

**Comment by Buffer0x7cd** [comment]
Do we need a development server guys? i can set it up one on aws or digital ocean if it will help ?

**Comment by tirtha4** [comment]
For now let's do a local run. If needed we'll do it tomorrow or later.

**Comment by Buffer0x7cd** [comment]
okay.

**Comment by bhawesh96** [comment]
If local setup is easy to go, then great.
Else, we can go about deploying it on DO or AWS as @Buffer0x7cd says

**Comment by ranjanmishra07** [comment]
$ git push
To https://github.com/tirtha4/nerdtalk.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/tirtha4/nerdtalk.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

.....I AM  GETTING THIS WHILE PUSHING

**Comment by bhawesh96** [comment]
Do a git pull
We merged a branch to master, hence

**Comment by ranjanmishra07** [comment]
I did git push @bhawesh96

**Comment by ranjanmishra07** [comment]
but how will we deploy for testing (on heroku,etc) as we have two package.json flile

**Comment by bhawesh96** [comment]
Just deploy the `server` directory. Need not care about `client` related files.
client can be deployed on github pages as well

**Comment by bhawesh96** [comment]
Can you please add instructions to start the `server` server
I did `npm i`
There's no start script

**Comment by bhawesh96** [comment]
Also, should we all connect on slack?
Gives mobility + more convenient (personally)

**Comment by Buffer0x7cd** [comment]
there is a start script in server

**Comment by Buffer0x7cd** [comment]
It would be good if we do not include client secret and other keys in code. using an environment variable will be good, @ranjanmishra07

**Comment by bhawesh96** [comment]
I didn't find it. Will get back shortly after dinner

**Comment by Buffer0x7cd** [comment]
There is one inside the server directory. you can start the server with running npm start there.

**Comment by bhawesh96** [comment]
`var config = require('../config');`

file named `config` doesn't exist
@Buffer0x7cd

**Comment by ranjanmishra07** [comment]
I just pushed again the updated files .Please see to that if you are still getting the error as i am not getting any error in my console @bhawesh96

**Comment by bhawesh96** [comment]
I saw your commit. You've moved the keys to `config` file and then imported it
The `config` file is expected to be in the `/server/auth` directory but it isn't there.
Can you please recheck

**Comment by bhawesh96** [comment]
I removed the config file and put the keys there itself

GITHUB AUTH WORKS WELL :1st_place_medal:

**Comment by ranjanmishra07** [comment]
@bhawesh96  thanks for doing , as i was going to do the same because of thhat error

**Comment by ranjanmishra07** [comment]
@bhawesh96  have you tested it with your view page .Is it working fine ? so that i can move to google login implementation

**Comment by bhawesh96** [comment]
Yes, it works well :+1:

**Comment by ranjanmishra07** [comment]
So tonight only we should finish google also ? then from tommow we will continue how to use getstream.io

**Comment by bhawesh96** [comment]
Yea, this would be great

**Comment by anubsinha** [comment]
Hi guys! So what are we shipping today? 
@bhawesh96 @Buffer0x7cd  @ranjanmishra07 @tirtha4

**Comment by tirtha4** [comment]
We got the GitHub authentication ready. Maybe the Google auth will be finished too.
So, out of the 5 requested feature, we got one done(almost)
We'll be shipping today's update around 11.

Yeah. We'll do the setup docs.

**Comment by ranjanmishra07** [comment]
Google auth will take 1 to 2 hours from now i guess .
Then I will jump to getstream.io and start working on it

**Comment by anubsinha** [comment]
Cool. Great teamwork. Okay. I will test this stuff by early morning, and we will set up a deployment tomorrow for the world to see it in all of its glory!

**Comment by bhawesh96** [comment]
Alright.
Meanwhile, we can start on the client side getstream code

**Comment by anubsinha** [comment]
Also, make sure everyone is sending their part of the code from their user accounts.

**Comment by tirtha4** [comment]
@bhawesh96  yeah, tomorrow let's think about the post component. I'm trying to Pace myself with react. We'll discuss the design and stuff.

**Comment by Buffer0x7cd** [comment]
I am going through mongoose and express docs. I will try to complete the post functionality and until morning.

**Comment by ranjanmishra07** [comment]
completed the google and github login api's code and also moved keys in a different file (now its working as expected )..
You can see the screenshots

**Comment by ranjanmishra07** [comment]
![screenshot 6](https://user-images.githubusercontent.com/21200740/35405061-09a94db6-022b-11e8-8a6b-66ffde4997f4.png)
![screenshot 7](https://user-images.githubusercontent.com/21200740/35405062-0a0fbb6e-022b-11e8-8d17-2714d1f11b9e.png)
![screenshot 8](https://user-images.githubusercontent.com/21200740/35405063-0a8a6e2c-022b-11e8-8d15-c33c0557bffa.png)

**Comment by ranjanmishra07** [comment]
I am committing this change for google and github updated codes  .Please test it with the frontend @bhawesh96

**Comment by bhawesh96** [comment]
Great!
@ranjanmishra07 
Is there any way for you to set 'allow-control-allow-origin'?

**Comment by ranjanmishra07** [comment]
![screenshot 9](https://user-images.githubusercontent.com/21200740/35405311-b9f29e02-022b-11e8-80c8-23d42ebcfb5b.png)

**Comment by ranjanmishra07** [comment]
and also created database , and users can be added after successful authentication to robomongo as of now (we will be moving to mongo labs later for remote database )

**Comment by ranjanmishra07** [comment]
I think i need to use cors middleware for that @bhawesh96 
.I totally forgot that , lets try after adding

**Comment by bhawesh96** [comment]
Yes please
I'm working with a chrome extension that manipulates CORS issues
a temporary hack. But needs to be worked upon asap
Let me know when done
@ranjanmishra07

**Comment by ranjanmishra07** [comment]
@bhawesh96  please try to do "npm i cors --save" in your directory because i am not able to install cors .

**Comment by bhawesh96** [comment]
in the client directory?

**Comment by bhawesh96** [comment]
@ranjanmishra07 
Somehow I'm getting stuck during oauth. I tried without the client side as well
Auth page of github/google opens and after authorising, it gets stuck, waiting for 127.0.0.1/3000

**Comment by ranjanmishra07** [comment]
Just now i checked with google call , i sent me object in json format as in previous screenshots within seconds @bhawesh96 
I dont know why it is getting stuck there , you are signing in through signed gmail right?
and yes please check for cors , because it can be a big issue as it is not getting installed (some fault in npm or my pc )

**Comment by ranjanmishra07** [comment]
it*

**Comment by bhawesh96** [comment]
![screenshot from 2018-01-26 08-47-09](https://user-images.githubusercontent.com/17593065/35423766-8722ab94-0275-11e8-81fa-921e3bdedc30.png)

Its getting stuck here on my system @ranjanmishra07

**Comment by ranjanmishra07** [comment]
@bhawesh 96 this issue is coming because you dont have running database in
your background i guess ? because gooes code is different from github , it
creates new user in the database and then sends the user object back

**Comment by bhawesh96** [comment]
This is thrown in the terminal - 
```
(node:6111) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
(node:6111) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ranjanmishra07** [comment]
do you have mongodb running as a service ..and robomongo setup  ?
Also please try this ...cooment res.json in googles route on successful
authentication and add "console.log(req.user) and check wat its throwing
inside terminal

**Comment by bhawesh96** [comment]
Nope
Mongodb is not running.  I don't have it installed

I already tried the console.log(req.user) thing, but that part is still unreachable I guess as I'm stuck before that

**Comment by bhawesh96** [comment]
![screenshot from 2018-01-26 09-09-16](https://user-images.githubusercontent.com/17593065/35424291-9b4101d6-0278-11e8-8339-efa5a1b32fa5.png)

I get this after 2-3 mins after authorising github account

**Comment by ranjanmishra07** [comment]
If mongo db is not running how will the user get created .thats why it is
showing failed to connect and mongoconnect error . without mongo db this
code wont work .
If you are not feeling like installing it then i will create a remote
database on mongolab and deploy it later...but once please try installing
mongodb as it will be good for local testing .

**Comment by bhawesh96** [comment]
Alright
I thought we handled that using mlab
I'll try installing mongodb. Anything else reqd?
Also, please put it in the README

**Comment by ranjanmishra07** [comment]
which is your view file for login page ? I will try to test with that

**Comment by bhawesh96** [comment]
Works now after setting up mongodb

**Comment by bhawesh96** [comment]
@ranjanmishra07 
I've included cors() on server side
Can you please check the implementation
Its in the latest pull request

**Comment by bhawesh96** [comment]
@ranjanmishra07 
please pull and check client on your system
do a npm start in client after npm start in server. Client will open on a different port

**Comment by ranjanmishra07** [comment]
sorry just woke ..i will check after sometime  @bhawesh96

**Comment by tirtha4** [comment]
@bhawesh96  I was working on the `AuthComponent.js` didn't notice your commit before pushing it. there. Might've been some conflict. I'll check.

**Comment by tirtha4** [comment]
Fixed.

Guys I'm closing this thread and starting a new one for today.. This one's getting crowded.
