### ISSUE TITLE
Share feature

### ISSUE THREAD

**Issue by bhawesh96** [opscaleindia/nerdtalk#20]
When user clicks on 'share' button, the post is to be shared in the NerdTalk network itself or is to be shared on other social media platforms like facebook etc?

**Comment by anubsinha** [comment]
@bhawesh96 
Just NerdTalk network. Share is a post which comes into our feed from a person you follow and now you want to propagate this post to all the users you have on your network.

**Comment by bhawesh96** [comment]
Got it
Thanks!
