### ISSUE TITLE
Pankaj

### ISSUE THREAD

**Issue by anubsinha** [opscaleindia/nerdtalk#3]
@pankajcoding 
Hi Pankaj, how is the progress? You can share daily updates in this thread.

**Comment by pankajcoding** [comment]
I have setup the basic skeleton of app, I also did some refresher tutorials on express and mongodb, now today I will try to design and code frontend pages.

**Comment by anubsinha** [comment]
@pankajcoding Okay. Good progress.

**Comment by pankajcoding** [comment]
Posts format will be like short blogs, right?

**Comment by anubsinha** [comment]
@pankajcoding Yes
