### ISSUE TITLE
Team Discussiong: General (Day 2)

### ISSUE THREAD

**Issue by tirtha4** [opscaleindia/nerdtalk#7]
Let's use this thread for today.
I guess the CORS issue has been resolved? 

# Team Call Meeting at 8pm today!

**Comment by bhawesh96** [comment]
No, it hasn't been resolved
I spoke to Ranjan, he said he'll be deploying server app on heroku. Lets try after that
Meanwhile, we can work on the Feed page @tirtha4 
I'll push what i've done for the Feed page

**Comment by tirtha4** [comment]
Cool. For temporary solution, I tried that Allow Control Allow Origin chrome plugin.

Also, instead of keeping the OAuth function within the AuthComponent.js, can you move it to a service file and import it from there? I think it'll be better to not keep those stuffs in component.

Yeah, let's look into the feed. @bhawesh96 
I updated the login page, now it look like this. Will do a logo later.
![home](https://user-images.githubusercontent.com/18365101/35427585-499be39c-0290-11e8-9615-69ccc94fc4f1.PNG)

**Comment by bhawesh96** [comment]
@tirtha4 
Once the auth is done successfully (after resolving the CORS issues), I'll move it to the service file

**Comment by bhawesh96** [comment]
To summarise the CORS issue -
Server app runs on `:3000` and client (making the login request) in `:3001`
We are supposed to make a request to `:3000/auth/google` for oAuth from the client app running on `:3001`
Error on console - 

`Failed to load http://localhost:3000/auth/github: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3001' is therefore not allowed access.`

**Comment by tirtha4** [comment]
Exactly, I've seen this before. Let's try to look for a solution to this.

I'm moving out now. Will be working again in the evening from 6. We need to think of the wireframe of the feed, how it should look and stuff. Can you draw a sketch of your idea and share? @bhawesh96  If you want you can use any online drawing tool like [draw.io](https://www.draw.io/)

## Again
### Team Meeting @8pm

**Comment by ranjanmishra07** [comment]
can we do meeting before 4 pm as its difficult to get on call after evening

**Comment by ranjanmishra07** [comment]
@bhawesh96  i am getting this issue while starting react app
![screenshot 10](https://user-images.githubusercontent.com/21200740/35428998-03c6f930-0298-11e8-86f8-e71db5324d46.png)

**Comment by ranjanmishra07** [comment]
fixed this issue as there was no streamService but was used in cardComponent 
.but getting this issue now @bhawesh96 
![screenshot 11](https://user-images.githubusercontent.com/21200740/35429362-bfd415e4-0299-11e8-8a99-a162dcad2a24.png)

**Comment by bhawesh96** [comment]
A moment please.
I'll push fresh code

**Comment by bhawesh96** [comment]
@ranjanmishra07 
Git pull and check now please

**Comment by Buffer0x7cd** [comment]
@tirtha4  I have fixed the connection problem with mlab. please check and merge the PR.

**Comment by Buffer0x7cd** [comment]
@ranjanmishra07 Are we going to have the auth routes directly in app file or separate routes directory?

**Comment by ranjanmishra07** [comment]
@bhawesh96  As we are only testing things now we will use this way for now , auth routes in app file .I dont want to complicate codes now , As one mistake in backend can cause many problems.
we will make a separate route file after testing

**Comment by ranjanmishra07** [comment]
![screenshot 12](https://user-images.githubusercontent.com/21200740/35430069-aff2d950-029c-11e8-9dd0-15d98816d5b5.png)

**Comment by ranjanmishra07** [comment]
mongo lab has been updated in the code . now our databse connection is remote.

**Comment by Buffer0x7cd** [comment]
@ranjanmishra07 I have made the same changes and issued a PR.

**Comment by ranjanmishra07** [comment]
Ranjan Mishra@dell07 MINGW64 /c/NERDTALK/nerdtalk/server (master)
$ npm install cors --save
npm ERR! Unexpected token < in JSON at position 233

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ranjan Mishra\AppData\Roaming\npm-cache\_logs\2018-01-26T08_00_25_968Z-debug.log

**Comment by ranjanmishra07** [comment]
cant get cors on my local system... i dont know whats the problem. Anyone please check installing cors package

**Comment by Buffer0x7cd** [comment]
try  rm package-lock.json and then npm install. it will  remove the npm error @ranjanmishra07

**Comment by Buffer0x7cd** [comment]
@bhawesh96  I am getting this error while running the react app
`./src/Components/HomeComponent/CardComponent.js
Module not found: Can't resolve '../../Services/StreamService' in '/home/reaper/repos/nerdtalk/client/src/Components/HomeComponent'`

**Comment by ranjanmishra07** [comment]
got the same error while doing rm package-lock.json

**Comment by ranjanmishra07** [comment]
@bhawesh96  can you please push your react code one more time

**Comment by Buffer0x7cd** [comment]
@tirtha4 Can you merge the PR please

**Comment by Buffer0x7cd** [comment]
I think all of us are pusing to different branches is slowing down because @tir tha4  have to do the merge again and again. if you guys are okay then we can set up a automerge so that it can merge the branches if there are no conflicts? @tirtha4 @bhawesh96 @ranjanmishra07

**Comment by tirtha4** [comment]
There was a conflict between @ranjanmishra07  and @Buffer0x7cd  commit in the app.js.

I think it's with the mongoose connection establishment. There are two connection requests. Can you guys check and decide which one to keep? I'm actually not on my machine. I've pulled the PR.

**Comment by Buffer0x7cd** [comment]
no problem we both have set up a mongo db connection. you can merge anyone @tirtha4

**Comment by ranjanmishra07** [comment]
My updated app.js code which contains mlab is already pushed .You can see that in the files under server/app.js

**Comment by tirtha4** [comment]
@ranjanmishra07  both of your requests are on the app.js files. Can you remove one and push directly to master?

**Comment by ranjanmishra07** [comment]
@tirtha4  can u help me how to do that , as i am not that good with git

**Comment by ranjanmishra07** [comment]
and also i added cors successfully.

**Comment by tirtha4** [comment]
No problem. Do a git pull. I just merged @Buffer0x7cd  PR.
currently in the App.js
```

mongoose.connect(db.url,()=>{

// mongoose.connect('mongodb://localhost:27017/nerdtalk',()=>{
//   console.log('connected to database');
// });
});
mongoose.connect('mongodb://raja:raja@ds115768.mlab.com:15768/nerdtalk',()=>{

  console.log('connected to database');

```
There're two mongoose connection requests, I hope they are for separate two destinations.

**Comment by Buffer0x7cd** [comment]
@ranjanmishra07 you don't need to specify the connection. I have added it to my PR. please remove the same from your commit, otherwise, it will cause a conflict.

**Comment by Buffer0x7cd** [comment]
@tirtha4  Would you like to set up an auto-merge so that you don't have to do it every time by yourself?

**Comment by ranjanmishra07** [comment]
how to do the auto merge

**Comment by Buffer0x7cd** [comment]
I am thinking about setting up a webhook. it will automatically get a notification when any of us push a commit to this repo in any branch. and if it can merge without any conflict then it will automatically merge the new branch with master

**Comment by Buffer0x7cd** [comment]
@ranjanmishra07 you don't have to set up anything. it will be handled by the webhook that I will set up.

**Comment by Buffer0x7cd** [comment]
@ranjanmishra07 @tirtha4 Now there are two DB connection requests in the master branch. :confused:

**Comment by ranjanmishra07** [comment]
@Buffer0x7cd  remove my db connection and then commit

**Comment by Buffer0x7cd** [comment]
@ranjanmishra07 Okay.

**Comment by bhawesh96** [comment]
Is the react issue resolved?

**Comment by ranjanmishra07** [comment]
Can you please your updated code once again @bhawesh96

**Comment by bhawesh96** [comment]
Sure

**Comment by ranjanmishra07** [comment]
@Buffer0x7cd   please add cors in the same way in the screenshot and then commit and push
![screenshot 13](https://user-images.githubusercontent.com/21200740/35432293-9904b048-02a5-11e8-96e4-6afaf66a8793.png)

**Comment by bhawesh96** [comment]
The react app breaks on my local too :|

**Comment by Buffer0x7cd** [comment]
@ranjanmishra07  Done. @tirtha4  you can merge the PR.

**Comment by bhawesh96** [comment]
I've fixed the bug
Please pull @ranjanmishra07

**Comment by bhawesh96** [comment]
There were issues in the last merge
<div id="root"> was deleted and <app-root> was added which caused bugs
Whoever did it, please be careful
Also, the server side app.js had an unclosed bracket

**Comment by ranjanmishra07** [comment]
everyone please test and then commit the change and leave a message here
before changing the code

On 26 Jan 2018 15:46, "Bhawesh Bhansali" <notifications@github.com> wrote:

There were issues in the last merge
was deleted and was added which caused bugs Whoever did it, please be
careful Also, the server side app.js had an unclosed bracket

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/opscaleindia/nerdtalk/issues/7#issuecomment-360739927>,
or mute the thread

**Comment by bhawesh96** [comment]
The CORS issue hasn't been resolved yet
Its to be done on the server end
Add `Access-Control-Allow-Origin` header is to be added while sending the request AFAIK

**Comment by bhawesh96** [comment]
@ranjanmishra07 @Buffer0x7cd 
Can you guys recheck the usage of `cors()`?

**Comment by Buffer0x7cd** [comment]
@tirtha4 @bhawesh96  @ranjanmishra07 It's not working because we have merged a previous pull request into the master.

**Comment by ranjanmishra07** [comment]
$ git pull
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.

I am getting this error while pulling

**Comment by bhawesh96** [comment]
`git status` and check which files you've changed
Maybe you can stash your changes and then pull

**Comment by ranjanmishra07** [comment]
On which port your react app is running ? @bhawesh96

**Comment by bhawesh96** [comment]
3001

**Comment by ranjanmishra07** [comment]
![screenshot 14](https://user-images.githubusercontent.com/21200740/35439725-f54bcbea-02c1-11e8-8a2d-9427accbc6f8.png)


I think we need to have folder structure like this to work react app with backend .
As in this angular working with app.js

**Comment by bhawesh96** [comment]
Can you send me the link to this code?

**Comment by ranjanmishra07** [comment]
Ranjan Mishra@dell07 MINGW64 /c/NERDTALK/nerdtalk/client (master)
$ npm start

> app@0.1.0 start C:\NERDTALK\nerdtalk\client
> PORT=3001 react-scripts start

'PORT' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@0.1.0 start: `PORT=3001 react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ranjan Mishra\AppData\Roaming\npm-cache\_logs\2018-01-26T12_30_22_546Z-debug.log
@bhawesh96  I am getting this in my terminal while accessing react app

**Comment by ranjanmishra07** [comment]
that angular with node code is in my pc

**Comment by ranjanmishra07** [comment]
https://github.com/ranjanmishra07/meanauthapp @bhawesh96  visit this page

**Comment by bhawesh96** [comment]
Remove `PORT=3001` from client's package.json 
Run server first and then run client. It'll prompt client app to run on another port automatically

**Comment by ranjanmishra07** [comment]
I have refactored the folder structure @tirtha4 @bhawesh96 @Buffer0x7cd  which looks as
![screenshot 15](https://user-images.githubusercontent.com/21200740/35441218-acb4aa44-02c8-11e8-88f8-8a7937477bf6.png)
So as to make the project look like real world project structure

**Comment by bhawesh96** [comment]
https://github.com/hexacta/react-express-starter-kit

@ranjanmishra07 
Check this

**Comment by ranjanmishra07** [comment]
should i push it

**Comment by bhawesh96** [comment]
Does it work after npm start?
Push it on branch
We'll fetch and run on local to check

**Comment by tirtha4** [comment]
@Buffer0x7cd the pull request you submitted, I can see you have cleaned up the clutter. I'll merge this. 👍

**Comment by tirtha4** [comment]
Hey guys just want to share something, @bhawesh96  @ranjanmishra07  @Buffer0x7cd 

I did `npm install` for the server, I got this
>npm ERR! Unexpected token < in JSON at position 233
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\TIRTHA\AppData\Roaming\npm-cache\_logs\2018-01-26T13_38_34_402Z-debug.log

As I can understand, there's some cross with npm and the lock file.
**Solution:** Remove the `package-lock.json` file and then do npm install. That helped, and also a new `package-lock.json` was generated.

**Comment by bhawesh96** [comment]
do rm-rf package-lock.json

**Comment by tirtha4** [comment]
@bhawesh96 @ranjanmishra07 @Buffer0x7cd
The current client and server have issues. So let's get on the call around the call and try to find a solution to this. I guess you guys have already noticed them and working on.

**CLIENT**

>  app@0.1.0 start F:\opscale\nerdtalk\client
>  PORT=3001 react-scripts start
> 
> 'PORT' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! app@0.1.0 start: `PORT=3001 react-scripts start`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the app@0.1.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:

**SERVER**

> server@1.0.0 start F:\opscale\nerdtalk\server
> node app.js

> module.js:557
>     throw err;
>     ^
> 
> Error: Cannot find module 'cors'
>     at Function.Module._resolveFilename (module.js:555:15)
>     at Function.Module._load (module.js:482:25)
>     at Module.require (module.js:604:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (F:\opscale\nerdtalk\server\app.js:7:10)
>     at Module._compile (module.js:660:30)
>     at Object.Module._extensions..js (module.js:671:10)
>     at Module.load (module.js:573:32)
>     at tryModuleLoad (module.js:513:12)
>     at Function.Module._load (module.js:505:3)
>     at Function.Module.runMain (module.js:701:10)
>     at startup (bootstrap_node.js:193:16)
>     at bootstrap_node.js:617:3
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! server@1.0.0 start: `node app.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the server@1.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\TIRTHA\AppData\Roaming\npm-cache\_logs\2018-01-26T13_57_24_011Z-debug.log
>

**Comment by ranjanmishra07** [comment]
@bhawesh96  the new folder structure was not working so we should stick to the old one as i saw on the net people use like that only how we were using .
So should i push the new changes (foldr structure)

**Comment by ranjanmishra07** [comment]
@tirtha4  those bugs are fixed . we have no issues starting server and client .The only issue is routing and connecting backend route with frontend

**Comment by bhawesh96** [comment]
We'll just delete the nerdtalk1 branch.

You can do `git checkout master` on your system and you'll be in sync with
remote master

**Comment by Buffer0x7cd** [comment]
@tirtha4  I have addressed those issues in my last PR. it should be fixed now

**Comment by Buffer0x7cd** [comment]
it was due to cors dependency have not been added to the package.json

**Comment by ranjanmishra07** [comment]
@bhawesh96  i cant pull from master remote master

**Comment by bhawesh96** [comment]
What error?

**Comment by ranjanmishra07** [comment]
auto merge failed

**Comment by bhawesh96** [comment]
probably you have some local changes then
do `git checkout .`
and then do a git pull again

**Comment by ranjanmishra07** [comment]
E325: ATTENTION
Found a swap file by the name "C:/NERDTALK/nerdtalk/.git/.MERGE_MSG.swp"
          owned by: Ranjan Mishra   dated: Thu Jan 25 22:23:30 2018
         file name: /c/NERDTALK/nerdtalk/.git/MERGE_MSG
          modified: YES
         user name: Ranjan Mishra   host name: dell07
        process ID: 19088
While opening file "C:/NERDTALK/nerdtalk/.git/MERGE_MSG"
             dated: Fri Jan 26 19:52:55 2018
      NEWER than swap file!

(1) Another program may be editing the same file.  If this is the case,
    be careful not to end up with two different instances of the same
    file when making changes.  Quit, or continue with caution.
(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r C:/NERDTALK/nerdtalk/.git/MER
GE_MSG"
    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file "C:/NERDTALK/nerdtalk/.git/.ME
RGE_MSG.swp"
    to avoid this message.

Swap file "C:/NERDTALK/nerdtalk/.git/.MERGE_MSG.swp" already exists!
-- More --

**Comment by bhawesh96** [comment]
Well, I cannot say why's this error.
Best way would be to just clone the repo again

**Comment by Buffer0x7cd** [comment]
@ranjanmishra07 Are working with VIM?

**Comment by ranjanmishra07** [comment]
@bhawesh96  can you please establish a router link in react app for login

**Comment by tirtha4** [comment]
Take a look at this https://www.npmjs.com/package/cors

**Comment by Buffer0x7cd** [comment]
Here is a question about the cors [issue](https://stackoverflow.com/questions/43276462/cors-issue-while-requesting-access-token-google-oauth-2/43276710)

**Comment by tirtha4** [comment]
https://developers.google.com/identity/sign-in/web/server-side-flow

https://developers.google.com/identity/protocols/OAuth2UserAgent

Did you guys read these?

**Comment by ranjanmishra07** [comment]
yeah ovio without going through it how would i have written server side code . @tirtha4

**Comment by Buffer0x7cd** [comment]
yeah @tirtha4 , that's what I was talking about giving the token from client to server.

**Comment by Buffer0x7cd** [comment]
@ranjanmishra07 @tirtha4 We don't get the token directly from Google. the google Oauth will send the response with a token attached after #. we need to get this token from the client and then send it to the server. the server will save this token and then we can use that token from the server side to get the information about the user.

**Comment by ranjanmishra07** [comment]
If you want to know how to use that visit passport js ,but that has already been done , so please concentrate on how to route a user when he clicks on login page so that he may be directed to server auth route .
and about cors it is used as same as our code in all the server side codes.
I dont see any problem with cors

**Comment by bhawesh96** [comment]
Alright
So we'll make a get request to github/Google's oAuth URLs and then read the
response and send to the server

**Comment by ranjanmishra07** [comment]
but we are getting the response from google url .what to change there , the user is getting stored in the db with id and email , if user is not there then it is getting created .

**Comment by Buffer0x7cd** [comment]
let's move on with the newsfeed and home page. we will clear the cors issue later @tirtha4 @bhawesh96 @ranjanmishra07

**Comment by ranjanmishra07** [comment]
yeah thats correct @Buffer0x7cd

**Comment by Buffer0x7cd** [comment]
we should start with defining API routes for the news feed and other operation. @ranjanmishra07

**Comment by bhawesh96** [comment]
Ok cool
I'll get back after dinner

**Comment by ranjanmishra07** [comment]
// enable cors
var corsOption = {
  origin: true,
  methods: 'GET,HEAD,PUT,PATCH,POST,DELETE',
  credentials: true,
  exposedHeaders: ['x-auth-token']
};
app.use(cors(corsOption));

**Comment by ranjanmishra07** [comment]
use this in node js file for cors .
I guess it will fix the issue .
@Buffer0x7cd @tirtha4 @bhawesh96

**Comment by tirtha4** [comment]
Now it works! server is working!

**Comment by bhawesh96** [comment]
Are latest changes there on master?

**Comment by ranjanmishra07** [comment]
no i have not commited any changes in master?
@bhawesh96

**Comment by bhawesh96** [comment]
@tirtha4 
Please push the code which works for you

**Comment by tirtha4** [comment]
Guys, there's an issue. Anub asked me to work on this project separately. So I guess I'll be moving out of the team. Can someone fork my current repo? You guys can use that as the master and work. I'll be removing this repo.

**Comment by ranjanmishra07** [comment]
@bhawesh96 have u can use help from this code for client side verification and routing for talking to server , 


onSuccess = (response) => {
  const token = response.headers.get('x-auth-token');
  response.json().then(user => {
    if (token) {
      this.setState({isAuthenticated: true, user: user, token: token});
    }
  });
};

onFailed = (error) => {
  alert(error);
};

render() {
  let content = !!this.state.isAuthenticated ?
    (
      <div>
        <p>Authenticated</p>
        <div>
          {this.state.user.email}
        </div>
        <div>
          <button onClick={this.logout} className="button" >
            Log out
          </button>
        </div>
      </div>
    ) :
    (
      <TwitterLogin loginUrl="http://localhost:4000/api/v1/auth/twitter"
                    onFailure={this.onFailed} onSuccess={this.onSuccess}
                    requestTokenUrl="http://localhost:4000/api/v1/auth/twitter/reverse"/>
//use localhost/auth/google/callback for request token url
// and need to generate client id and secret
    );

  return (
    <div className="App">
      {content}
    </div>
  );

**Comment by bhawesh96** [comment]
Yea, that's not an issue
We were stuck at the part right above `.onSuccess()` ie. the request
@tirtha4 seems to have resolved it now

**Comment by Buffer0x7cd** [comment]
@tirtha4 @bhawesh96 @ranjanmishra07  So we need to work separately from now on?

**Comment by bhawesh96** [comment]
Looks like that

**Comment by ranjanmishra07** [comment]
I don't understand what you mean by work separately @Buffer0x7cd
